server:
  port: 8768
spring:
  application:
    name: springcloud-configclient
  cloud:
    config:
      profile: test
      label: master
      uri: http://localhost:8767/
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/