server:
  port: 8767
spring:
  application:
    name: springcloud-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wenleigang/springcloud-learning
          search-paths: configuration
      label: master
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/